---
- name: Install Apache.
  hosts: centos
  become: true

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
      notify:
        - Restart memcached

    - name: Restart memcached
      ansible.builtin.service:
        name: memcached
        state: restarted

  tasks:
    - name: Update Env Vars.
      ansible.builtin.lineinfile:
        dest: "~/.bashrc"
        regexp: "^ENV_VAR="
        line: "ENV_VAR=value"
      become: false

    - name: Ensure Apache is installed.
      ansible.builtin.yum:
        name:
          - httpd
        state: present

    - name: Copy test config file.
      ansible.builtin.copy:
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
        mode: "2770"
      notify:
        - Restart apache
