---
- name: Deploy App on TomCat server
  hosts: all
  become: true
  become_method: runas
  become_user: cs\service_account
  become_flags: ignore_errors=false

  vars_files:
    - vars.yaml
  
  handlers:
    - ansible.builtin.import_tasks:
        - handlers/apache.yaml

  pre_tasks:
    - name: Stop Tomcat service
      ansible.windows.win_service:
        name: Tomcat9.5
        state: stopped

  tasks:
    - name: Stop Running tasks
      ansible.windows.win_shell:
        - cmd
      become: true

    - name: Copy App Dir files
      ansible.windows.win_copy:
        src: local.war
        dest: E:\apps\

    - name: Copy Config files
      ansible.windows.win_copy:
        src: test.war
        dest: E:\apps\config
    
    - name: Config 
      ansible.builtin.import_tasks:
        - tasks/test.yaml

  post_tasks:
    - name: Restart Tomcat Services
      ansible.windows.win_service:
        name: Tomcat9.5
        state: started

