---
- name: Install Solar on inode Server
  hosts: solar
  become: true

  vars_files:
    - vars.yaml

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 36000
  
  handlers:
    - name: Restart Solar 
      ansible.builtin.service:
        - name : Solar
          state: restarted
  
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name:
          - openjdk-8-jdk
        state: present

    - name: Download Solar
      ansible.builtin.get_url:
        url: "{{ solr_url }}"
        dest: "{{ download_dir }}/solr-{{solr_version}}.tgz"
        checksum: "{{ solr_checksum }}"
    
    - name: Expand Solar
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{solr_version}}/README.md"
    
    - name: Run Installation Script
      ansible.builtin.command: >
        {{ download_dir }}/solr-{{solr_version}}/bin/install.sh
        {{download_dir}}/solr-{{ solr_version }}.tgz 
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{solr_dir}}/bin/solr
    
    - name: Ensure solr is stared and enabled at boot
      ansible.builtin.service:
        name: solr
        state: started
        enabled: true
