---
- name: Install Apache
  hosts: app
  become: true
  gather_facts: false
  tasks:
    - name: Update OS
      ansible.builtin.yum:
        name:
          - wget
          - bzip2
        state: present
    - name: Install Apache
      ansible.builtin.yum:
        name:
          - httpd
          - httpd-devel
        state: present
    - name: Copy Config files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /tmp
        - src: httpd-vhosts.conf
          dest: /tmp
    - name: Ensure Apache is up and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true