---
- name: Install Apache
  hosts: app
  become: true
  tasks:
    - name: Update OS
      ansible.builtin.yum:
        name:
          - wget
          - bzip2
        state: latest
    - name: Install Apache
      ansible.builtin.yum:
        name:
          - httpd
          - httpd-devel
        state: present
    - name: Ensure Apache is up and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true